# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='route',
            field=models.CharField(auto_created=True, db_index=True, default='Default title', max_length=40),
        ),
    ]
